name: flutter_broadcasts
description: A plugin for sending and receiving broadcasts with Android intents and iOS notifications.
version: 0.5.0
author: Kevin Latusinski <me@kevlatus.de>
repository: https://github.com/kevlatus/flutter_broadcasts

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.18.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.kevlatus.flutter_broadcasts
        pluginClass: FlutterBroadcastsPlugin
      ios:
        pluginClass: FlutterBroadcastsPlugin
